
### Realizar Notificação

POST /api/v1/evidences HTTP/1.1
Host: localhost:8083
Content-Type: multipart/form-data; boundary=arquivo

--arquivo
Content-Disposition: form-data; name=evidence; filename=teste.png
Content-Type: image/jpeg

< ./evidencias-api/images.jpeg
--arquivo--
