
### Get all users

GET /api/v1/users HTTP/1.1
Host: localhost:8080
Accept: application/json

### Create a new User

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "email": "batata@potato.com",
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}

### Post an invalid user

POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "password": "1234RT56",
    "handle": "papas",
    "name": "Kartofel",
    "roles": [
        "ROLE_USER"
    ],
    "company": "potato inc"
}